# Generated by Django 4.1.1 on 2022-10-04 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SalesHistory",
            fields=[
                (
                    "saleshistory_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("sku", models.CharField(max_length=50)),
                ("tenate_id", models.CharField(max_length=55)),
                ("node", models.CharField(max_length=50)),
                ("channle", models.CharField(max_length=50)),
                ("salesman_email", models.CharField(max_length=50)),
                ("salesman_name", models.CharField(max_length=50)),
                ("actual_sales_volume", models.IntegerField()),
                ("actual_sales_volume_uom", models.CharField(max_length=50)),
                ("actual_sales_value", models.IntegerField()),
                ("actual_sales_value_uom", models.CharField(max_length=50)),
            ],
        ),
    ]
