# Generated by Django 3.2 on 2022-10-04 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleshistory',
            name='actual_sales_value',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='saleshistory',
            name='actual_sales_value_uom',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='saleshistory',
            name='actual_sales_volume',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='saleshistory',
            name='actual_sales_volume_uom',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='saleshistory',
            name='channle',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='saleshistory',
            name='node',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='saleshistory',
            name='salesman_email',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='saleshistory',
            name='salesman_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='saleshistory',
            name='sku',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='saleshistory',
            name='tenate_id',
            field=models.CharField(max_length=55, null=True),
        ),
    ]
